### PR TITLE
Lpatch tinydata

### PR DESCRIPTION
**Pull request by liamhuber**
Patching test failures on #949

### CODE REVIEW

**Comment by liamhuber** [comment]
Notebook tests are just hanging (>30mins).

In `pyiron_workflow`, `pympipool` requires a modification of the path so that the unit tests can be found... perhaps something similar is happening here with the notebooks? @jan-janssen, as far as I can see the `pympipool` tests never run the example notebook there, so maybe you have some insight on this.

For now I'm just going try-and-see by getting rid of `pympipool` from the notebook.

**Comment by liamhuber** [comment]
Windows and notebooks runs are both still going after 12 minutes 👎

**Comment by liamhuber** [comment]
Windows took a while (20 mins) but finished. Notebooks got through checkout but were "pending" on the actual run for over an hour

**Review by pmrv — APPROVED** [review]
lgtm

**Pull request merged**
