### PR TITLE
Revert "Image job: Convert DotDict to ImputList"

### PR DESCRIPTION
**Pull request by liamhuber**
Reverts pyiron/pyiron_contrib#17

I forgot the conversation about how this depends on Jan's PR. I'll get Jan's merged, then hopefully still use this for converting the names down to lower case.

### CODE REVIEW

**Comment by liamhuber** [comment]
I merged and reverted, but this would undo a lot of the stuff in [pr 18](https://github.com/pyiron/pyiron_contrib/pull/18). I had hoped to cherry pick just the commit where the capitalization was changed, but my merge/revert seems to have squashed [pr 17](https://github.com/pyiron/pyiron_contrib/pull/17). 

I'll look real quick to see if I can figure out how to grab (just that commit)[https://github.com/pyiron/pyiron_contrib/pull/17/commits/353f7c6ee241b3cc0f4d1577b20856b94a79915d] but I have a meeting in 5 and might not get it done in time. @niklassiemer you could practice your GitHub magic if I don't manage ;)

**Comment by liamhuber** [comment]
You know what, I just checked the source code and it is *already* using the correct lower case.
I'm not going to pretend I fully understand what I just did 😬 but it looks like it worked anyhow...

**Comment by jan-janssen** [comment]
I am sorry - I guess that was my mistake - I wanted to see the changes in a pull request to add comments - then I got interrupted and did not set the pull request to draft ... .

**Comment by niklassiemer** [comment]
I tried to understand what happened, but I failed. As far as I see, the current master is identical to my ImageJob branch. Furthermore, the PR #18 has only commits which are already in the master. So, applying this should not change anything, or am I mistaken?
In PR #17 I also had used the commit of PR #16 which was the one I needed.

**Pull request closed without merging**
