### PR TITLE
Rename protocol job names

### PR DESCRIPTION
**Pull request by raynol-dsouza**
Since the cluster database limits strings like 'job_name' to less than 20 characters, all the protocol job names have been shortened to fit within this character limit.

Note: ProtocolQMMM has NOT been modified.

### CODE REVIEW

**Review by liamhuber — APPROVED** [review]
👍

**Comment by raynol-dsouza** [comment]
@liamhuber I do not follow why the checks are failing...

**Comment by liamhuber** [comment]
@rads, did you just manually re-trigger the tests? It looked like something going wrong on the CI side. I tried looking at our organization account to check quotas etc and didn't find anything, but when I came back here the failed tests (notebooks and coverage) we re-running...

**Comment by liamhuber** [comment]
If you didn't manually re-trigger I guess it was a server-side hiccup for the CI providers.

**Comment by raynol-dsouza** [comment]
Manual trigger.

**Comment by liamhuber** [comment]
> Manual trigger.

Ok, well it's failing the same way anyhow.

I can tell you *what* is happening, but not in any useful way: the automated CI runners don't have access to the scripts they need to do the CI tests we ask them to do. But this is probably already totally evident since I'm just re-phrasing the error message.

*Why* the CI services are suddenly complaining is a mystery to me. Let me go peek at old merges that ran OK...

**Comment by liamhuber** [comment]
Ok, [this PR from a few hours ago](https://github.com/pyiron/pyiron_contrib/pull/151/checks?check_run_id=2435533370) ran the exact same line `Run ./.ci_support/build_notebooks.sh` totally fine. 

In particular, we're getting the shell error code 126. This will come up if you try to execute a file that does not have execution privileges (from among read/write/execute). E.g. `touch foo.exe; foo.exe; echo $?` shows that trying to run the random file `foo.exe` gives error 126.

So now the question is why the CI doesn't have this permission? Is it possible the permission of the file really got changed inside your branch? Can you check the permissions on your local machine on that branch? If they don't include execution, try modifying accordingly and pushing to see if that clears it up.

**Comment by liamhuber** [comment]
@rads uh-huh, yep, right at the start of the diff it's modifying the relevant file: " .ci_support/build_notebooks.sh  100755 → 100644"

**Comment by liamhuber** [comment]
> @rads uh-huh, yep, right at the start of the diff it's modifying the relevant file: " .ci_support/build_notebooks.sh 100755 → 100644"

I glossed over this reading the diff for review, but it's certainly not good. I'm also surprised it shows as an "empty file" there, since it [shouldn't be](https://github.com/pyiron/pyiron_contrib/blob/master/.ci_support/build_notebooks.sh)

**Comment by raynol-dsouza** [comment]
`build_notebooks.sh` executes now, so that's good.

**Review by liamhuber — APPROVED** [review]
So I don't know why coveralls is still complaining, but (a) all the unit tests pass, (b) the integration tests pass, and (c) no weird files are showing up in the diff anymore, only things we really do want to change. So I'm content to merge.

**Comment by caglayanoaras** [comment]
I have no problem for now. It is working on my side

**Review by caglayanoaras — APPROVED** [review]

**Pull request merged**
