### PR TITLE
Remove hdf assignment already handled by the super() call

### PR DESCRIPTION
**Pull request by niklassiemer**
After the discussion in [pyiron_base](https://github.com/pyiron/pyiron_base/pull/50#issue-502077335) I also got rid of the additional hdf if clauses in the image job.

### CODE REVIEW

**Comment by liamhuber** [comment]
What I really get scared by is that the `hdf` argument is now *not used*. Either your code is doing what it's supposed to and there is a heinous problem upstream that we have meaningless variables in our signature, or your code should use `_hdf5` only as a backup when `hdf=None`.

I suspect your code is perfect, which is actually unfortunate in this case ;)

**Comment by jan-janssen** [comment]
At @liamhuber it is used in `super(ImageJob, self).to_hdf(hdf=hdf, group_name=group_name)`

**Comment by niklassiemer** [comment]
As @jan-janssen pointed out, `hdf` is used in the `super` call. There `self._hdf` is set to the provided `hdf` if not None. Therefore, we were checking this at each layer while it was already taken care of.

**Comment by liamhuber** [comment]
Aha, so the goal is to eventually get rid of this `hdf` argument everywhere? 

If we pass in a non-None `hdf`, why don't we also want to use it in this method? Is this just a slightly dangerous naming convention, where we have an argument `hdf` but then don't use it for the `hdf` argument of sub-methods called?

**Comment by jan-janssen** [comment]
The argument for the current solution is that the code developer only needs to take care of `self._hdf` or `self.project_hdf` and does not need to take care of the check if `hdf` is set or not. A more clean solution would be to have static methods which just take `hdf` and do not use `self._hdf` or `self.project_hdf` and then basically use a decorator which handles the switch in case `hdf` is not set.

**Comment by niklassiemer** [comment]
If we pass in a non-None `hdf` we will use exactly this hdf, since `self._hdf=hdf` in this case due to the `super` call. Of course we could retain the `if hdf==None: hdf = self._hdf`, however after the `super` call one could also just write `hdf=self._hdf`

**Comment by liamhuber** [comment]
> If we pass in a non-None `hdf` we will use exactly this hdf, since `self._hdf=hdf` in this case due to the `super` call. 

Ahhahaha, aye, there's the rub. I accept this behaviour, but I definitely don't like it.

```
class Foo:
    def meth(self, arg):
        self._arg = arg

class Bar(Foo):
    def meth(self, arg):
        super().meth(arg)
        return self._arg + 2
```

^^ This is certainly legal, but for developers who are working on `Bar` or child classes thereof it's super cruel.

**Comment by liamhuber** [comment]
Given that this is the reality of the situation though, I now very clearly see the benefit of not re-checking the `if-None` case and am 100% behind this PR.

**Review by liamhuber — APPROVED** [review]
Given that this is the reality of the situation though, I now very clearly see the benefit of not re-checking the if-None case and am 100% behind this PR.

**Comment by niklassiemer** [comment]
> Ahhahaha, aye, there's the rub. I accept this behaviour, but I definitely don't like it.
> 
> ```python
> class Foo:
>     def meth(self, arg):
>         self._arg = arg
> 
> class Bar(Foo):
>     def meth(self, arg):
>         super().meth(arg)
>         return self._arg + 2
> ```
> 
> ^^ This is certainly legal, but for developers who are working on `Bar` or child classes thereof it's super cruel.

Do I understand correctly, that you say it is cruel since the variable `self._arg` of `class Bar` appears out of nowhere?

**Comment by liamhuber** [comment]
> Do I understand correctly, that you say it is cruel since the variable `self._arg` of `class Bar` appears out of nowhere?

Yes, that's all I mean. To me it is just a violation of "explicit is better than implicit". Here we pass in an argument, but then never use it in the code we're presently writing, but rather only pass it to a super which silently updates some other attribute and *that* is then the piece of information we're *actually* using in our new code. It's a legal architecture choice but...

confusing

**Comment by liamhuber** [comment]
And I should be clear: I don't *like* it, but I don't have any better ideas at the moment either so, like 0% judgement here. Just something we should keep in the back of our minds as a yellow flag.

**Pull request merged**
