### PR TITLE
Atomicrex fix non modal mode 

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Review by pmrv — APPROVED** [review]
I hadn't checked the `from_hdf`, but this fix makes sense.  `to_object()` should work on all `InputList` sub-classes.  I looked up that the "OBJECT" field in the `to_object()` is not actually used, so it shouldn't be a problem if that is incorrectly set.

**Comment by jan-janssen** [comment]
```
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/srv/conda/envs/notebook/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyiron_base/job/generic.py", line 1670, in multiprocess_wrapper
    job_wrap.job.run_static()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyiron_base/job/generic.py", line 773, in run_static
    self.run()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyiron_base/generic/util.py", line 213, in decorated
    return function(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyiron_base/job/generic.py", line 684, in run
    self._run_if_collect()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyiron_base/job/generic.py", line 1424, in _run_if_collect
    self.collect_output()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyiron_contrib/atomistic/atomicrex/atomicrex_job.py", line 100, in collect_output
    self.potential._parse_final_parameters(parameter_lines)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyiron_contrib/atomistic/atomicrex/potential_factory.py", line 124, in _parse_final_parameters
    f"Can't find {identifier} in potential, probably something went wrong during parsing.\n"
ValueError: Can't find V_CuCu in potential, probably something went wrong during parsing.
Fitting parameters of screening functions probably doesn't work right now
```

**Comment by jan-janssen** [comment]
@pmrv there seems to be an issue with the hierarchy of `input lists`: 

```
{'pair_interactions': {'V_CuCu': {'species': ['*', '*'],
   'parameters': {'D0': {'param': 'D0',
     'start_val': 1.0,
     'enabled': True,
     'reset': False,
     'min_val': 0,
     'max_val': 3.5,
     'tag': None,
     'fitable': True,
     'final_value': None},
    'r0': {'param': 'r0',
     'start_val': 1.8,
     'enabled': True,
     'reset': False,
     'min_val': 1.65,
     'max_val': 1.95,
     'tag': None,
     'fitable': True,
     'final_value': None},
    'beta': {'param': 'beta',
     'start_val': 2,
     'enabled': True,
     'reset': False,
     'min_val': 0.5,
     'max_val': 4,
     'tag': None,
     'fitable': True,
     'final_value': None},
    'S': {'param': 'S',
     'start_val': 2,
     'enabled': True,
     'reset': False,
     'min_val': 1.01,
     'max_val': 10,
     'tag': None,
     'fitable': True,
     'final_value': None},
    'delta': {'param': 'delta',
     'start_val': 0,
     'enabled': True,
     'reset': False,
     'min_val': -1,
     'max_val': 1,
     'tag': None,
     'fitable': True,
     'final_value': None}},
   'is_screening_function': False,
   'identifier': 'V_CuCu',
   'screening': {'species': ['*', '*'],
    'parameters': {'cutoff': {'param': 'cutoff',
      'start_val': 7,
      'enabled': False,
      'reset': False,
      'min_val': None,
      'max_val': None,
      'tag': None,
      'fitable': False,
      'final_value': None},
     'rc': {'param': 'rc',
      'start_val': 1,
      'enabled': False,
      'reset': False,
      'min_val': None,
      'max_val': None,
      'tag': None,
      'fitable': True,
      'final_value': None},
     'alpha': {'param': 'alpha',
      'start_val': 0.2,
      'enabled': False,
      'reset': False,
      'min_val': None,
      'max_val': None,
      'tag': None,
      'fitable': True,
      'final_value': None},
     'exponent': {'param': 'exponent',
      'start_val': 1,
      'enabled': False,
      'reset': False,
      'min_val': None,
      'max_val': None,
      'tag': None,
      'fitable': True,
      'final_value': None}},
    'is_screening_function': True,
    'identifier': 'V_screen'}}},
 'electron_densities': {'CuCu_rho': {'identifier': 'CuCu_rho',
   'cutoff': 7,
   'derivative_left': -25,
   'derivative_right': 0,
   'species': ['*', '*'],
   'parameters': {'node_0.5': {'param': 'node',
     'start_val': 10,
     'enabled': False,
     'reset': False,
     'min_val': None,
     'max_val': None,
     'tag': None,
     'fitable': True,
     'final_value': None,
     'x': 0.5},
    'node_1.0': {'param': 'node',
     'start_val': 3,
     'enabled': True,
     'reset': False,
     'min_val': 1,
     'max_val': 3,
     'tag': None,
     'fitable': True,
     'final_value': None,
     'x': 1.0},
    'node_2.0': {'param': 'node',
     'start_val': 0.7,
     'enabled': True,
     'reset': False,
     'min_val': 0.0,
     'max_val': 1,
     'tag': None,
     'fitable': True,
     'final_value': None,
     'x': 2.0},
    'node_3.0': {'param': 'node',
     'start_val': 0.35,
     'enabled': True,
     'reset': False,
     'min_val': 0.0,
     'max_val': 0.8,
     'tag': None,
     'fitable': True,
     'final_value': None,
     'x': 3.0},
    'node_4.0': {'param': 'node',
     'start_val': 0.2,
     'enabled': True,
     'reset': False,
     'min_val': 0.0,
     'max_val': 0.6,
     'tag': None,
     'fitable': True,
     'final_value': None,
     'x': 4.0},
    'node_5.0': {'param': 'node',
     'start_val': 0.1,
     'enabled': True,
     'reset': False,
     'min_val': 0.0,
     'max_val': 0.4,
     'tag': None,
     'fitable': True,
     'final_value': None,
     'x': 5.0},
    'node_6.0': {'param': 'node',
     'start_val': 0.05,
     'enabled': True,
     'reset': False,
     'min_val': 0.0,
     'max_val': 0.2,
     'tag': None,
     'fitable': True,
     'final_value': None,
     'x': 6.0},
    'node_7.0': {'param': 'node',
     'start_val': 0.0,
     'enabled': False,
     'reset': False,
     'min_val': None,
     'max_val': None,
     'tag': None,
     'fitable': True,
     'final_value': None,
     'x': 7.0}}}},
 'embedding_energies': {'F_CuCu': {'identifier': 'F_CuCu',
   'cutoff': 100,
   'derivative_left': 0,
   'derivative_right': 0,
   'species': ['*', '*'],
   'parameters': {'node_0.0': {'param': 'node',
     'start_val': 0,
     'enabled': False,
     'reset': False,
     'min_val': None,
     'max_val': None,
     'tag': None,
     'fitable': True,
     'final_value': None,
     'x': 0.0},
    'node_5.0': {'param': 'node',
     'start_val': -1,
     'enabled': True,
     'reset': False,
     'min_val': -3.5,
     'max_val': 0,
     'tag': None,
     'fitable': True,
     'final_value': None,
     'x': 5.0},
    'node_10.0': {'param': 'node',
     'start_val': -1,
     'enabled': True,
     'reset': False,
     'min_val': -3.5,
     'max_val': 0,
     'tag': None,
     'fitable': True,
     'final_value': None,
     'x': 10.0},
    'node_15.0': {'param': 'node',
     'start_val': -1.6,
     'enabled': True,
     'reset': False,
     'min_val': -3.5,
     'max_val': 0,
     'tag': None,
     'fitable': True,
     'final_value': None,
     'x': 15.0},
    'node_20.0': {'param': 'node',
     'start_val': -1,
     'enabled': True,
     'reset': False,
     'min_val': -3.5,
     'max_val': 0,
     'tag': None,
     'fitable': True,
     'final_value': None,
     'x': 20.0},
    'node_25.0': {'param': 'node',
     'start_val': 0.0,
     'enabled': True,
     'reset': False,
     'min_val': -3.5,
     'max_val': 3.5,
     'tag': None,
     'fitable': True,
     'final_value': None,
     'x': 25.0},
    'node_30.0': {'param': 'node',
     'start_val': 2.0,
     'enabled': True,
     'reset': False,
     'min_val': -1,
     'max_val': 5,
     'tag': None,
     'fitable': True,
     'final_value': None,
     'x': 30.0},
    'node_40.0': {'param': 'node',
     'start_val': 5.0,
     'enabled': True,
     'reset': False,
     'min_val': 0,
     'max_val': 7,
     'tag': None,
     'fitable': True,
     'final_value': None,
     'x': 40.0}}}},
 'identifier': 'EAM',
 'export_file': 'output.eam.fs',
 'rho_range_factor': 2.0,
 'resolution': 10000,
 'species': ['*', '*']}
```

vs. 

```
{'pair_interactions': {'pair_interactions': [],
  'electron_densities': [],
  'embedding_energies': [],
  'identifier': {'V_CuCu': {'species': ['*', '*'],
    'parameters': {'D0': {'param': 'D0',
      'start_val': 1.0,
      'enabled': True,
      'reset': False,
      'min_val': 0,
      'max_val': 3.5,
      'tag': None,
      'fitable': True,
      'final_value': None},
     'r0': {'param': 'r0',
      'start_val': 1.8,
      'enabled': True,
      'reset': False,
      'min_val': 1.65,
      'max_val': 1.95,
      'tag': None,
      'fitable': True,
      'final_value': None},
     'beta': {'param': 'beta',
      'start_val': 2,
      'enabled': True,
      'reset': False,
      'min_val': 0.5,
      'max_val': 4,
      'tag': None,
      'fitable': True,
      'final_value': None},
     'S': {'param': 'S',
      'start_val': 2,
      'enabled': True,
      'reset': False,
      'min_val': 1.01,
      'max_val': 10,
      'tag': None,
      'fitable': True,
      'final_value': None},
     'delta': {'param': 'delta',
      'start_val': 0,
      'enabled': True,
      'reset': False,
      'min_val': -1,
      'max_val': 1,
      'tag': None,
      'fitable': True,
      'final_value': None}},
    'is_screening_function': False,
    'identifier': 'V_CuCu',
    'screening': {'species': ['*', '*'],
     'parameters': {'cutoff': {'param': 'cutoff',
       'start_val': 7,
       'enabled': False,
       'reset': False,
       'min_val': None,
       'max_val': None,
       'tag': None,
       'fitable': False,
       'final_value': None},
      'rc': {'param': 'rc',
       'start_val': 1,
       'enabled': False,
       'reset': False,
       'min_val': None,
       'max_val': None,
       'tag': None,
       'fitable': True,
       'final_value': None},
      'alpha': {'param': 'alpha',
       'start_val': 0.2,
       'enabled': False,
       'reset': False,
       'min_val': None,
       'max_val': None,
       'tag': None,
       'fitable': True,
       'final_value': None},
      'exponent': {'param': 'exponent',
       'start_val': 1,
       'enabled': False,
       'reset': False,
       'min_val': None,
       'max_val': None,
       'tag': None,
       'fitable': True,
       'final_value': None}},
     'is_screening_function': True,
     'identifier': 'V_screen'}}},
  'export_file': None,
  'rho_range_factor': None,
  'resolution': None,
  'species': None},
 'electron_densities': {'pair_interactions': [],
  'electron_densities': [],
  'embedding_energies': [],
  'identifier': {'CuCu_rho': {'identifier': 'CuCu_rho',
    'cutoff': 7,
    'derivative_left': -25,
    'derivative_right': 0,
    'species': ['*', '*'],
    'parameters': {'node_0.5': {'param': 'node',
      'start_val': 10,
      'enabled': False,
      'reset': False,
      'min_val': None,
      'max_val': None,
      'tag': None,
      'fitable': True,
      'final_value': None,
      'x': 0.5},
     'node_1.0': {'param': 'node',
      'start_val': 3,
      'enabled': True,
      'reset': False,
      'min_val': 1,
      'max_val': 3,
      'tag': None,
      'fitable': True,
      'final_value': None,
      'x': 1.0},
     'node_2.0': {'param': 'node',
      'start_val': 0.7,
      'enabled': True,
      'reset': False,
      'min_val': 0.0,
      'max_val': 1,
      'tag': None,
      'fitable': True,
      'final_value': None,
      'x': 2.0},
     'node_3.0': {'param': 'node',
      'start_val': 0.35,
      'enabled': True,
      'reset': False,
      'min_val': 0.0,
      'max_val': 0.8,
      'tag': None,
      'fitable': True,
      'final_value': None,
      'x': 3.0},
     'node_4.0': {'param': 'node',
      'start_val': 0.2,
      'enabled': True,
      'reset': False,
      'min_val': 0.0,
      'max_val': 0.6,
      'tag': None,
      'fitable': True,
      'final_value': None,
      'x': 4.0},
     'node_5.0': {'param': 'node',
      'start_val': 0.1,
      'enabled': True,
      'reset': False,
      'min_val': 0.0,
      'max_val': 0.4,
      'tag': None,
      'fitable': True,
      'final_value': None,
      'x': 5.0},
     'node_6.0': {'param': 'node',
      'start_val': 0.05,
      'enabled': True,
      'reset': False,
      'min_val': 0.0,
      'max_val': 0.2,
      'tag': None,
      'fitable': True,
      'final_value': None,
      'x': 6.0},
     'node_7.0': {'param': 'node',
      'start_val': 0.0,
      'enabled': False,
      'reset': False,
      'min_val': None,
      'max_val': None,
      'tag': None,
      'fitable': True,
      'final_value': None,
      'x': 7.0}}}},
  'export_file': None,
  'rho_range_factor': None,
  'resolution': None,
  'species': None},
 'embedding_energies': {'pair_interactions': [],
  'electron_densities': [],
  'embedding_energies': [],
  'identifier': {'F_CuCu': {'identifier': 'F_CuCu',
    'cutoff': 100,
    'derivative_left': 0,
    'derivative_right': 0,
    'species': ['*', '*'],
    'parameters': {'node_0.0': {'param': 'node',
      'start_val': 0,
      'enabled': False,
      'reset': False,
      'min_val': None,
      'max_val': None,
      'tag': None,
      'fitable': True,
      'final_value': None,
      'x': 0.0},
     'node_5.0': {'param': 'node',
      'start_val': -1,
      'enabled': True,
      'reset': False,
      'min_val': -3.5,
      'max_val': 0,
      'tag': None,
      'fitable': True,
      'final_value': None,
      'x': 5.0},
     'node_10.0': {'param': 'node',
      'start_val': -1,
      'enabled': True,
      'reset': False,
      'min_val': -3.5,
      'max_val': 0,
      'tag': None,
      'fitable': True,
      'final_value': None,
      'x': 10.0},
     'node_15.0': {'param': 'node',
      'start_val': -1.6,
      'enabled': True,
      'reset': False,
      'min_val': -3.5,
      'max_val': 0,
      'tag': None,
      'fitable': True,
      'final_value': None,
      'x': 15.0},
     'node_20.0': {'param': 'node',
      'start_val': -1,
      'enabled': True,
      'reset': False,
      'min_val': -3.5,
      'max_val': 0,
      'tag': None,
      'fitable': True,
      'final_value': None,
      'x': 20.0},
     'node_25.0': {'param': 'node',
      'start_val': 0.0,
      'enabled': True,
      'reset': False,
      'min_val': -3.5,
      'max_val': 3.5,
      'tag': None,
      'fitable': True,
      'final_value': None,
      'x': 25.0},
     'node_30.0': {'param': 'node',
      'start_val': 2.0,
      'enabled': True,
      'reset': False,
      'min_val': -1,
      'max_val': 5,
      'tag': None,
      'fitable': True,
      'final_value': None,
      'x': 30.0},
     'node_40.0': {'param': 'node',
      'start_val': 5.0,
      'enabled': True,
      'reset': False,
      'min_val': 0,
      'max_val': 7,
      'tag': None,
      'fitable': True,
      'final_value': None,
      'x': 40.0}}}},
  'export_file': None,
  'rho_range_factor': None,
  'resolution': None,
  'species': None},
 'identifier': 'EAM',
 'export_file': 'output.eam.fs',
 'rho_range_factor': 2.0,
 'resolution': 10000,
 'species': {'pair_interactions': [],
  'electron_densities': [],
  'embedding_energies': [],
  'identifier': ['*', '*'],
  'export_file': None,
  'rho_range_factor': None,
  'resolution': None,
  'species': None}}
```

**Comment by jan-janssen** [comment]
The classes are initialised empty and afterwards the content of the HDF5 file is reloaded.

**Comment by pmrv** [comment]
So the second one is the wrong one?

**Comment by jan-janssen** [comment]
> So the second one is the wrong one?

yes

**Comment by pmrv** [comment]
I have to look at the HDF5, testing it one the mybinder right now.

**Comment by pmrv** [comment]
Ah, think I know the issue, I'll open a PR.

**Comment by jan-janssen** [comment]
@pmrv fixed the issue, so @Leimeroth you can merge this.

**Pull request merged**
