### PR TITLE
Improve TrainingContainer

### PR DESCRIPTION
**Pull request by sudarsan-surendralal**
Included a function to return all stored structures (also energies and forces) as a list

### CODE REVIEW

**Review by pmrv — CHANGES_REQUESTED** [review]
I like the filter functionality and the tests, but I'm not sure if  `get_data_list` gets that much more mileage than 
```python
p = tc.to_pandas()
p.atoms, p.energy, ...
```
Maybe we can just make a property for the filter function and use it in `to_pandas()`.   I'm a bit worried that converting to lists is going to take forever with large training sets.

If you want to keep it that's also ok with that, but then I'd change the name to `to_list` so that it is consistent with `to_pandas`.

EDIT: I realize that iterating over a dataframe is a bit cumbersome, but then I'd say we add a `__iter__` to the container that yields each structure, energy, forces and number of atoms.

**Comment by sudarsan-surendralal** [comment]
> 
> 
> I like the filter functionality and the tests, but I'm not sure if `get_data_list` gets that much more mileage than
> 
> ```python
> p = tc.to_pandas()
> p.atoms, p.energy, ...
> ```

But is `p.atoms` giving us the pyiron atoms? I thought we still need to convert this which is what motivated this function

**Comment by pmrv** [comment]
> > I like the filter functionality and the tests, but I'm not sure if `get_data_list` gets that much more mileage than
> > ```python
> > p = tc.to_pandas()
> > p.atoms, p.energy, ...
> > ```
> 
> But is `p.atoms` giving us the pyiron atoms? I thought we still need to convert this which is what motivated this function (and to avoid working with data frames which is useful for beginners)

Ah fair, no it will give the ase atoms.  That's mainly because our Atoms gives an error when pickled, but I couldn't look into it yet.  It's ok then for me, just change the name.

**Review by jan-janssen — APPROVED** [review]
Looks good to me - feel free to merge it, then we can create a new release for testing

**Pull request merged**
