### PR TITLE
Bump base, atomistics, and h5io_browser

### PR DESCRIPTION
**Pull request by liamhuber**
Accidentally committed this directly to main without noticing and it passed all the tests there, so I guess it should be good 🤦‍♂️ 

Now as a branch...

### CODE REVIEW

**Comment by liamhuber** [comment]
> > Accidentally committed this directly to main without noticing and it passed all the tests there, so I guess it should be good 🤦‍♂️ 
> > 
> > Now as a branch...
> 
> Maybe we should finally protect the main branch from direct push ;) 

Yeah, gonna do that as soon as I get home! I understand the rationale for the rule now 😂

**Comment by liamhuber** [comment]
> > Accidentally committed this directly to main without noticing and it passed all the tests there, so I guess it should be good 🤦‍♂️
> > Now as a branch...
> 
> Maybe we should finally protect the main branch from direct push ;)

@niklassiemer did you add the rule in the last couple hours? My reading of the currently-in-place rule is that it should have stopped what I did, so if you just added it then 🚀 but if it's been there all along then I've misunderstood the rules and we need something stricter!

**Comment by niklassiemer** [comment]
> > > Accidentally committed this directly to main without noticing and it passed all the tests there, so I guess it should be good 🤦‍♂️
> > > Now as a branch...
> > 
> > Maybe we should finally protect the main branch from direct push ;)
> 
> @niklassiemer did you add the rule in the last couple hours? My reading of the currently-in-place rule is that it should have stopped what I did, so if you just added it then 🚀 but if it's been there all along then I've misunderstood the rules and we need something stricter!

No, I did not alter the rules here! We might need to explicitly evaluate what is possible on a dummy repo...

**Comment by liamhuber** [comment]
> No, I did not alter the rules here! We might need to explicitly evaluate what is possible on a dummy repo...

Ah, yikes. I just went ahead and used this repo, but modifying just a comment in some random file -- I'm not super fussed about keeping the git history pristine.

Turns out we need to _also_ [check a box](https://stackoverflow.com/questions/58541814/how-to-protect-branch-with-require-pull-request-reviews-before-merging/58542669#58542669) preventing admins from ignoring the rules. Because otherwise they ignore them by default 😝

**Comment by niklassiemer** [comment]
:lol: fair enough! Just check the box every time you stumble on it then - I think we are just as prone to accidental pushes as everyone else xD

**Comment by liamhuber** [comment]
Yeah 😂 I didn't go through and click it exhaustively, but I agree we should click it as it comes up and I did for a couple of the usual suspects

**Pull request closed without merging**
