### PR TITLE
Include pyiron-data in the dependencies

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by liamhuber** [comment]
@jan-janssen just FYI, with repos using the centralized CI you only need to update the dependency in `.ci_support/environement.yml` and a bot will take care of docs and binder. Of course no harm is caused doing it manually either, I'm just trying to sell `pyiron/actions` a little 😉

**Comment by liamhuber** [comment]
Indeed, tests run fine with `pyiron-data` explicitly included.

**Comment by jan-janssen** [comment]
@liamhuber I do not understand why you closed this pull request, as it fixes the current issue until we have a better solution.

**Comment by jan-janssen** [comment]
Only include `pyiron-data` in the notebooks environment https://github.com/pyiron/pyiron_contrib/pull/893

**Pull request closed without merging**
