### PR TITLE
Add workflow to update the environment.yml in dependabot PRs

### PR DESCRIPTION
**Pull request by niklassiemer**

### CODE REVIEW

**Comment by niklassiemer** [comment]
@muh-hassani  could you please make and add a new `DEPENDABOT_WORKFLOW_TOKEN`?

**Comment by niklassiemer** [comment]
@muh-hassani could you also check if there is a `CODACY_PROJECT_TOKEN` since the Coverage workflow seems to expect but not find one? I am kind of confused since the coverage was working here, was it not?

**Comment by muh-hassani** [comment]
> 
> 
> @muh-hassani could you also check if there is a `CODACY_PROJECT_TOKEN` since the Coverage workflow seems to expect but not find one? I am kind of confused since the coverage was working here, was it not?

I just checked and `CODACY_PROJECT_TOKEN` already exists in the list of the secrets. I have rerun the workflow. Let's see if the issue persists.

**Comment by muh-hassani** [comment]
@niklassiemer it failed. I understood what the issue is. The branch you are trying to merge is from your own fork, where the token is not defined.

**Comment by niklassiemer** [comment]
Thanks a lot! Sorry for not paying attention to where the branch actually is located...

**Pull request merged**
