### PR TITLE
First draft of quantum espresso interface based on ASE

### PR DESCRIPTION
**Pull request by jan-janssen**
Copied from https://github.com/jan-janssen/pyiron-quantum-espresso

### CODE REVIEW

**Comment by jan-janssen** [comment]
The example is updated to use pyiron_contrib https://github.com/jan-janssen/pyiron-quantum-espresso

**Comment by jan-janssen** [comment]
Suggestion from Marvin https://github.com/Lonitch/qeAPI

**Comment by jan-janssen** [comment]
Cython interface for quantum espresso https://gitlab.com/shaoxc/qepy/-/tree/master

**Comment by niklassiemer** [comment]
The FFT grid can be specified in the `&SYSTEM` section by providing values for `nr1, nr2, nr3` (hard grid) or `nr1s, nr2s, nr3s` (smooth grid) in `pw.x` calculations - see 
https://www.quantum-espresso.org/Doc/INPUT_PW.html#idm294

**Comment by jan-janssen** [comment]
Maybe also take a look at https://github.com/aiidateam/qe-tools

**Comment by liamhuber** [comment]
@jan-janssen the only thing I'm not a fan of here and in #294 is that they use outdated input classes (`GenericParameters`, while #286 uses `DataContainer` and I already merged it). If you think it's feasible for you to update both/either of these PRs before merging that would be preferable; if you don't have time with this I'm also comfortable to just merge them as-is -- it is contrib after all.

**Pull request closed without merging**
